name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: build
        run: |
          npm install
          npm run clean
          npm run build
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: deploy
        run: |
          git config --global user.email s929459939@gmail.com
          git config --global user.name cuzfinal
          npm run deploy
        
